#!/bin/bash

# Find the directory that contains the physical script file
REALDIR=$(readlink "$0" | xargs dirname)

# Set flask application python script target and start on 5001
if [[ ! -z "$REALDIR" ]]; then
	# Activate the python virtual environment
	source $REALDIR/modules/bin/activate
	export FLASK_APP="$REALDIR/app/Telemetry.py"
else
	source ./modules/bin/activate
	export FLASK_APP="app/Telemetry.py"
fi

flask run -p 5001